name: unified_dream247
description: Unified e-commerce and fantasy gaming app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  get: ^4.6.6
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.2
  
  # Network
  dio: ^5.4.0
  graphql_flutter: ^5.1.2
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Routing
  go_router: ^12.1.3
  
  # UI Components
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_screenutil: ^5.9.0
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  dartz: ^0.10.1
  
  # Payment
  razorpay_flutter: ^1.3.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
